### ISSUE TITLE
Can you provide some wiki about how to use?)

### ISSUE THREAD

**Issue by OpakAlex** [K2InformaticsGmbH/erloci#19]

**Comment by c-bik** [comment]
Added a very basic wiki for quick start, check it out.
I plan do the in depth API documentation through edoc slowly.

Hope this [wiki](https://github.com/K2InformaticsGmbH/erloci/wiki) helps for now for you get started.

Suggestions and PR are always most welcome.

**Comment by OpakAlex** [comment]
Thanks, i am working with ecto adapter for orracle.

**Comment by c-bik** [comment]
No problem. Sounds interesting. Are you planning to use erloci in your adapter?

**Comment by OpakAlex** [comment]
Yes, i want use OCI, so i need erloci as adapter for oracle.

**Comment by c-bik** [comment]
Cool. Feel free to let me know if I can help you with any erloci specifics.
Also, please close this issue if you are happy with the wiki.

**Comment by OpakAlex** [comment]
yes, thank you!
