### ISSUE TITLE
Problem with binding vars

### ISSUE THREAD

**Issue by OpakAlex** [K2InformaticsGmbH/erloci#21]
When i try insert some values to table, i have this error:
```
Assertion failed: ((*it).is_tuple() && (*it).length() == 3 && (*it)[0].is_binary() && (*it)[1].is_any_int() && (*it)[2].is_any_int()), function map_schema_to_bind_args, file c_src/erloci_drv/marshal.cpp, line 297.
```

My table: `"CREATE TABLE \"schema_migrations\" (\"version\" NUMBER, \"inserted_at\" DATE)"`

My insert: 
```
"INSERT INTO \"schema_migrations\" (\"inserted_at\",\"version\") VALUES (:inserted_at, :version)"
[inserted_at: {{2016, 1, 6}, {14, 11, 39, 0}}, version: 0]
After mapping:
[{<<120, 116, 1, 6, 14, 11, 39>>, 0}]

**Comment by OpakAlex** [comment]
This happens when i send atoms not binary. This fixed. But i have another problem:
`{:error, {4280744, "Unsupported type in bind"}}`

`bind_args = [{":version", 'SQLT_INT'}, {":inserted_at", 'SQLT_DAT'}]`
`args = [{<<120, 116, 1, 6, 15, 0, 12>>, 0}]`

**Comment by c-bik** [comment]
Please try binaries as variable names.

Like:
```erlang
bind_args = [{<<":version">>, 'SQLT_INT'}, {<<":inserted_at">>, 'SQLT_DAT'}]
args = [{0, <<120, 116, 1, 6, 15, 0, 12>>}]
```
_Note:_ `args` _also needs to match_ `bind_args` _sequence_

**Comment by OpakAlex** [comment]
Yes, i understand, also in elixir `'SQLT_INT'` must be `: SQLT_INT`

**Comment by c-bik** [comment]
I have no elixir-fu :P. So, did it work?

I am curious. Is your plugin is in opensource already?

**Comment by OpakAlex** [comment]
we working on it. yes this bug fixed :)
https://github.com/api-hogs/ecto-oracle
