### ISSUE TITLE
Why not use lager for logger

### ISSUE THREAD

**Issue by newsdy** [K2InformaticsGmbH/erloci#28]
The code will appear to be very clear in using lager instead of the oci_logger.

**Comment by newsdy** [comment]
And i think, the logger should remove because it probably reduce the performance of the driver.If so, the driver will be more and more lightweight

**Comment by c-bik** [comment]
oci_logger receives port logs over TCP. Erlang logs are callbacks. Any logging backend can be plugged in through these callbacks.

**Comment by newsdy** [comment]
i see, thanks, i will close the issue
