### ISSUE TITLE
`mkdir -p priv` only from Makefiles (all platforms)

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/erloci#36]
@c-bik after https://github.com/K2InformaticsGmbH/erloci/commit/b44c82bf5b44b98ad3e56a356134a5c3700a099b erloci is not compiled anymore on OS X, workaround for me was to remove the mkdir part and manually add the priv folder for now, did not try on linux.

**Comment by c-bik** [comment]
@acautin Same/Similar bug was reported by @shamis for windows too:
```sh
git clone ...
rebar compile
rebar clean
rebar compile
```
... didn't work

Fix was https://github.com/K2InformaticsGmbH/erloci/commit/3f12865a1829cfc4ebd1ed11d57229c40bdb7668

I think similar situation exists for Linux+OSX. I will confirm/fix for Linux and then getback to you for OSX verification.
