### ISSUE TITLE
Very long ROWIDs for index organized tables

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/erloci#37]
Hi Bikram

it seems that Oracle 12 uses very long and dynamic rowids for certain tables (e.g. index organized tables):

![image](https://cloud.githubusercontent.com/assets/1941407/23857951/3cd19cc4-07ff-11e7-9147-ea270d805917.png)

Please check the bufferspace allocation for queries with columns of type ROWID

**Comment by c-bik** [comment]
Hi Stefan (@stoch),

Our OracleXE test DB (free) at K2 isn't capable of partitioning:
```sh
ORA-00439: feature not enabled: Partitioning
```
and acording to [this](https://community.oracle.com/thread/2217585) free versions of Oracle probably still doesn't.

Do you know any other way of creating long ROWIDs (longer than 19 characters) without using "Partitioning"?

As per [current code](https://github.com/K2InformaticsGmbH/erloci/blob/master/c_src/erloci_lib/ocistmt.cpp#L541) its truncated at 19 characters, which was ok for `SQLT_RID`
However in Oracle [documentation](https://docs.oracle.com/cd/A87860_01/doc/appdev.817/a76975/oci03typ.htm) this type is no longer valid:
```sh
(1) This type is valid only for version 7.x OCI calls. Oracle OCI release 8 applications should use the ROWID descriptor (type 104).
```
The new type `SQLT_RDD` uses a descriptor based ROWID and [`OCIRowidToChar`](https://docs.oracle.com/cd/B10501_01/appdev.920/a96584/oci16102.htm) for string conversion.

I need to develop this support against a DB which has such ROWIDs.

Where in stag/prod can I do this?

**Comment by cjbj** [comment]
To test UROWIDs, try:

```sql
drop table myiot;
create table myiot(c1 number, c2 varchar2(3000), primary key(c1, c2)) organization index;
insert into myiot values (1,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
);
commit;

select rowid from myiot;
```

**Comment by c-bik** [comment]
@cjbj Thanks. The SQL snippet really helped!

Now I am seeing UROWID:
![image](https://cloud.githubusercontent.com/assets/913008/23904360/e51145b0-08c7-11e7-8143-70943255a386.png)

However it seems that I can't trust the field length information from [`OCIAttrGet(OCI_DTYPE_PARAM, OCI_ATTR_DATA_SIZE)`](https://github.com/K2InformaticsGmbH/erloci/blob/master/c_src/erloci_lib/ocistmt.cpp#L399)
![image](https://cloud.githubusercontent.com/assets/913008/23904527/74ee0452-08c8-11e7-8217-ac065341c151.png)

**TBD**
* UROWID support in `insert`, `update` statements
* Add test case

**Comment by cjbj** [comment]
Maybe @anthony-tuininga can comment on what he did in https://github.com/oracle/odpi/blob/v2.0.0-beta.1/src/dpiRowid.c#L71-L126

**Comment by anthony-tuininga** [comment]
Sure. You can get the length of the rowid by calling OCIRowidToChar() with a buffer size of 0. See here:

https://github.com/oracle/odpi/blob/v2.0.0-beta.1/src/dpiRowid.c#L89-L91

Once you have done that you can allocate the memory you require and then call OCIRowidToChar() with the correct length.

**Comment by anthony-tuininga** [comment]
Be aware that if you use that function with the UTF-16 character set the data is still returned in ASCII characters.

**Comment by c-bik** [comment]
@anthony-tuininga and @cjbj Thanks.

I did something similar. But need to cleanup that code.
