### ISSUE TITLE
query execute failure on SBS test installation

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/erloci#62]
Problem processing command: error:function_clause
[{<<"query">>,[{<<"connection">>,<<"g2gDZAAIb2NpX3BvcnRnZAAhc2JzZ3VpQHZpbWFwZ2V0LXNic2gwMS5pdC5id25zLmNoAABaIwAAARECYgA6n4A=">>},{<<"qstr">>,<<"SELECT\r\n    *\r\nFROM\r\n    dba_users">>},{<<"conn_id">>,<<"133876732">>},{<<"binds">>,null}]}]
[{oci_adapter,process_log_binds,[undefined],[{file,"c:/Program Files (x86)/Jenkins/workspace/sbsgui/_build/default/lib/dderl/src/oci_adapter.erl"},{line,739}]},{oci_adapter,process_query,5,[{file,"c:/Program Files (x86)/Jenkins/workspace/sbsgui/_build/default/lib/dderl/src/oci_adapter.erl"},{line,676}]},{oci_adapter,process_cmd,6,[{file,"c:/Program Files (x86)/Jenkins/workspace/sbsgui/_build/default/lib/dderl/src/oci_adapter.erl"},{line,233}]},{dderl_session,spawn_process_call,8,[{file,"c:/Program Files (x86)/Jenkins/workspace/sbsgui/_build/default/lib/dderl/src/dderl_session.erl"},{line,645}]}]

@shamis can you please analyze the possible reason for this. 

This is the installation:

![image](https://user-images.githubusercontent.com/1941407/44626727-0143c180-a922-11e8-9174-4cfbc76bdef6.png)

**Comment by c-bik** [comment]
@stefan `oci_adapter` is in DDErl. This issue should be moved there too!

**Comment by acautin** [comment]
@stoch this is bug on dderl and was fixed with a patch that is probably missing on the installation. 

Ref: https://github.com/K2InformaticsGmbH/dderl/issues/537
